import Navigation from "../components/nav";
import Footer from "../components/footer";
import styles from './PageLayout.module.scss';

import Head from 'next/head';

const PageLayout = ({ children, pageTitle }) => {
  return (
    <>
      <Head>
        <title>{`Creatrix - ${pageTitle}`} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.pageContainer}>
        <Navigation />
          <main className={styles.main}>{children}</main>
        <Footer />
      </div>
    </>
  )
}

export default PageLayout;